-- .fledgling-init.sql — generated by install-fledgling.sql v0.2.0
-- Profile: analyst
-- Modules: sandbox, code, repo, conversations, docs, dr_fledgling, help, source, structural

.headers off
.mode csv
.output /dev/null

LOAD duckdb_mcp;
LOAD duck_tails;
LOAD markdown;
LOAD read_lines;
LOAD sitting_duck;

SET VARIABLE session_root = COALESCE(getvariable('session_root'), NULLIF(getenv('FLEDGLING_ROOT'), ''), getenv('PWD'));
SET VARIABLE conversations_root = COALESCE(getvariable('conversations_root'), NULLIF(getenv('CONVERSATIONS_ROOT'), ''), getenv('HOME') || '/.claude/projects');

-- Literal-backed macros for MCP tool templates (getvariable returns NULL in that context)
CREATE OR REPLACE MACRO _resolve(p) AS CASE WHEN p IS NULL THEN NULL WHEN p[1] = '/' THEN p ELSE '/mnt/aux-data/teague/Projects/judgementalmonad.com/' || p END;
CREATE OR REPLACE MACRO _session_root() AS '/mnt/aux-data/teague/Projects/judgementalmonad.com';
SET VARIABLE fledgling_version = '0.2.0';
SET VARIABLE fledgling_profile = 'analyst';
SET VARIABLE fledgling_modules = ['sandbox', 'code', 'repo', 'conversations', 'docs', 'dr_fledgling', 'help', 'source', 'structural'];
SET VARIABLE _help_path = '.fledgling-help.md';

-- Fledgling: Path Resolution & Sandbox Setup
--
-- Sets up path resolution macros for converting relative paths to absolute.
-- Used by all tool SQL templates to work with DuckDB's allowed_directories.
--
-- Two resolution strategies:
--   resolve(p)      — uses getvariable('session_root'). Works in direct SQL
--                      and macro bodies, but NOT in MCP tool templates
--                      (getvariable returns NULL in duckdb_mcp execution context).
--   _resolve(p)     — hardcoded literal root. Works everywhere including
--                      MCP tool templates. Use in mcp_publish_tool() SQL.
--   _session_root() — returns the bare session root literal. Use in tool
--                      templates that need the root path directly.
--
-- resolve() is defined here. _resolve() and _session_root() must be created
-- BEFORE this file loads, with the session root baked into the macro body:
--   - bin/fledgling creates them via duckdb -cmd (bash variable expansion)
--   - conftest.py creates them via con.execute() (Python string interpolation)
--
-- DuckDB macros are text-substituted at call time, so getvariable() in a
-- macro body runs in the caller's context. In MCP tool templates, that
-- context has no access to session variables → getvariable returns NULL.
-- The _resolve/_session_root macros avoid this by containing only literals.
-- They can't be defined in pure SQL because there's no dynamic DDL in DuckDB.
--
-- REQUIRES: session_root variable AND _resolve/_session_root macros must
-- be set before loading this file.
--
-- From CLI (bin/fledgling launcher):
--   duckdb -cmd "SET VARIABLE session_root = '$ROOT'" \
--          -cmd "CREATE ... MACRO _resolve(p) ..." \
--          -cmd "CREATE ... MACRO _session_root() ..." \
--          -init init-fledgling-analyst.sql
--
-- From Python (tests):
--   con.execute("SET VARIABLE session_root = '/path'")
--   con.execute("CREATE ... MACRO _resolve(p) ...")
--   con.execute("CREATE ... MACRO _session_root() ...")
--   load_sql(con, "sandbox.sql")
--
-- Filesystem lockdown (allowed_directories, enable_external_access)
-- is handled by the init script, not here, so tests can load
-- sandbox.sql without restricting tmp_path access.
--
-- See: https://github.com/duckdb/duckdb/issues/21102
--   (allowed_directories check runs before file_search_path resolution)

-- resolve: Variable-backed path resolution.
-- Works in direct SQL and macro bodies, but NOT in MCP tool templates.
-- Absolute paths (starting with /) pass through unchanged.
-- NULL input returns NULL (safe for optional params).
CREATE OR REPLACE MACRO resolve(p) AS
    CASE WHEN p IS NULL THEN NULL
         WHEN p[1] = '/' THEN p
         ELSE getvariable('session_root') || '/' || p
    END;

;
-- Fledgling: Code Intelligence Macros (sitting_duck)
--
-- Semantic code analysis powered by sitting_duck's AST parsing.
-- Replaces grep-based code search with structure-aware queries.

-- find_definitions: Find function, class, or variable definitions.
-- The core code search tool — replaces grep for "where is X defined?"
--
-- Examples:
--   SELECT * FROM find_definitions('**/*.py');
--   SELECT * FROM find_definitions('src/**/*.py', 'parse%');
CREATE OR REPLACE MACRO find_definitions(file_pattern, name_pattern := '%') AS TABLE
    SELECT
        file_path,
        name,
        semantic_type_to_string(semantic_type) AS kind,
        start_line,
        end_line,
        peek AS signature
    FROM read_ast(file_pattern)
    WHERE is_definition(semantic_type)
      AND name != ''
      AND name LIKE name_pattern
    ORDER BY file_path, start_line;

-- find_calls: Find function/method call sites.
-- Answers "where is this function called?"
--
-- Examples:
--   SELECT * FROM find_calls('**/*.py');
--   SELECT * FROM find_calls('src/**/*.py', 'connect%');
CREATE OR REPLACE MACRO find_calls(file_pattern, name_pattern := '%') AS TABLE
    SELECT
        file_path,
        name,
        start_line,
        peek AS call_expression
    FROM read_ast(file_pattern)
    WHERE is_call(semantic_type)
      AND name LIKE name_pattern
    ORDER BY file_path, start_line;

-- find_imports: Find import/include statements.
-- Answers "what does this file depend on?"
--
-- Examples:
--   SELECT * FROM find_imports('**/*.py');
CREATE OR REPLACE MACRO find_imports(file_pattern) AS TABLE
    SELECT
        file_path,
        name,
        peek AS import_statement,
        start_line
    FROM read_ast(file_pattern)
    WHERE is_import(semantic_type)
    ORDER BY file_path, start_line;

-- code_structure: Get a structural overview of files.
-- Shows the top-level definitions in a file/directory.
--
-- Examples:
--   SELECT * FROM code_structure('src/main.py');
--   SELECT * FROM code_structure('src/**/*.py');
CREATE OR REPLACE MACRO code_structure(file_pattern) AS TABLE
    SELECT
        file_path,
        name,
        semantic_type_to_string(semantic_type) AS kind,
        start_line,
        end_line,
        end_line - start_line + 1 AS line_count
    FROM read_ast(file_pattern)
    WHERE is_definition(semantic_type)
      AND name != ''
      AND depth <= 2
    ORDER BY file_path, start_line;

-- complexity_hotspots: Find the most complex functions in a codebase.
-- Returns functions ranked by cyclomatic complexity with structural metrics.
-- Useful for identifying code that needs refactoring or careful review.
--
-- Note: requires materializing the AST into a temp table because
-- ast_function_metrics takes a table reference, not a file pattern.
-- This macro handles that internally.
--
-- Examples:
--   SELECT * FROM complexity_hotspots('src/**/*.py');
--   SELECT * FROM complexity_hotspots('src/**/*.py', 10);
CREATE OR REPLACE MACRO complexity_hotspots(file_pattern, n := 20) AS TABLE
    WITH ast AS (
        SELECT * FROM read_ast(file_pattern)
    ),
    metrics AS (
        SELECT * FROM ast_function_metrics(ast)
    )
    SELECT
        file_path,
        name,
        lines,
        cyclomatic,
        conditionals,
        loops,
        return_count,
        max_depth
    FROM metrics
    ORDER BY cyclomatic DESC
    LIMIT n;

-- function_callers: Find all call sites for a named function across a codebase.
-- Answers "who calls X?" — the reverse of find_calls which shows what a file calls.
-- Groups by calling file and shows the enclosing function for each call site.
--
-- Examples:
--   SELECT * FROM function_callers('src/**/*.py', 'parse_config');
--   SELECT * FROM function_callers('**/*.py', 'validate');
CREATE OR REPLACE MACRO function_callers(file_pattern, func_name) AS TABLE
    WITH calls AS (
        SELECT
            file_path,
            start_line,
            node_id
        FROM read_ast(file_pattern)
        WHERE is_call(semantic_type)
          AND name = func_name
    ),
    enclosing AS (
        SELECT
            file_path,
            name,
            semantic_type_to_string(semantic_type) AS kind,
            start_line AS def_start,
            end_line AS def_end
        FROM read_ast(file_pattern)
        WHERE is_definition(semantic_type)
          AND semantic_type_to_string(semantic_type) IN
              ('DEFINITION_FUNCTION', 'DEFINITION_CLASS', 'DEFINITION_MODULE')
          AND name != ''
    ),
    matched AS (
        SELECT
            c.file_path,
            c.start_line AS call_line,
            e.name AS caller_name,
            e.kind AS caller_kind,
            e.def_end - e.def_start AS scope_size,
            row_number() OVER (
                PARTITION BY c.file_path, c.start_line
                ORDER BY e.def_end - e.def_start
            ) AS rn
        FROM calls c
        LEFT JOIN enclosing e
            ON c.file_path = e.file_path
           AND c.start_line BETWEEN e.def_start AND e.def_end
    )
    SELECT file_path, call_line, caller_name, caller_kind
    FROM matched
    WHERE rn = 1
    ORDER BY file_path, call_line;

-- module_dependencies: Map internal import relationships across a codebase.
-- Shows which modules import which, with fan-in count (how many modules
-- depend on each target). Filters to imports matching a given package prefix.
--
-- Examples:
--   SELECT * FROM module_dependencies('src/**/*.py', 'myapp');
--   SELECT * FROM module_dependencies('lib/**/*.py', 'lib');
CREATE OR REPLACE MACRO module_dependencies(file_pattern, package_prefix) AS TABLE
    WITH raw_imports AS (
        SELECT DISTINCT
            file_path,
            regexp_extract(peek, 'from (' || package_prefix || '[a-zA-Z0-9_.]*)', 1)::VARCHAR AS target_module
        FROM read_ast(file_pattern)
        WHERE is_import(semantic_type)
          AND peek LIKE '%from ' || package_prefix || '%'
    ),
    edges AS (
        SELECT
            replace(replace(
                regexp_extract(file_path, '((?:' || package_prefix || ')[a-zA-Z0-9_./]*)\.py$', 1),
            '/', '.'), '__init__', '') AS source_module,
            target_module
        FROM raw_imports
        WHERE target_module != ''
    )
    SELECT
        source_module,
        target_module,
        count(*) OVER (PARTITION BY target_module) AS fan_in
    FROM edges
    WHERE source_module != ''
    ORDER BY source_module, target_module;


;
-- Fledgling: Repository Intelligence Macros (duck_tails)
--
-- Structured access to git repository state. Replaces git CLI
-- commands with composable, queryable results.

-- recent_changes: What changed recently in the repository.
-- The most common git query — replaces `git log --oneline`.
--
-- Examples:
--   SELECT * FROM recent_changes();
--   SELECT * FROM recent_changes(10);
--   SELECT * FROM recent_changes(5, '/path/to/repo');
CREATE OR REPLACE MACRO recent_changes(n := 10, repo := '.') AS TABLE
    SELECT
        commit_hash[:8] AS hash,
        author_name AS author,
        author_date AS date,
        message
    FROM git_log(repo)
    LIMIT n;

-- branch_list: List all branches with current branch marked.
-- Replaces `git branch -a`.
--
-- Examples:
--   SELECT * FROM branch_list();
--   SELECT * FROM branch_list('/path/to/repo');
CREATE OR REPLACE MACRO branch_list(repo := '.') AS TABLE
    SELECT
        branch_name,
        commit_hash[:8] AS hash,
        is_current,
        is_remote
    FROM git_branches(repo)
    ORDER BY is_current DESC, is_remote, branch_name;

-- tag_list: List all tags with metadata.
-- Replaces `git tag -l`.
--
-- Examples:
--   SELECT * FROM tag_list();
CREATE OR REPLACE MACRO tag_list(repo := '.') AS TABLE
    SELECT
        tag_name,
        commit_hash[:8] AS hash,
        tagger_name,
        tagger_date,
        message,
        is_annotated
    FROM git_tags(repo)
    ORDER BY tagger_date DESC NULLS LAST;

-- repo_files: List all tracked files at a given revision.
-- Replaces `git ls-tree`.
--
-- Examples:
--   SELECT * FROM repo_files('HEAD');
--   SELECT * FROM repo_files('HEAD', '/path/to/repo');
CREATE OR REPLACE MACRO repo_files(rev := 'HEAD', repo := '.') AS TABLE
    SELECT
        file_path,
        file_ext,
        size_bytes,
        kind,
        is_text
    FROM git_tree(repo, rev)
    ORDER BY file_path;

-- file_at_version: Read a file as it existed at a specific revision.
-- Replaces `git show revision:path`.
--
-- Examples:
--   SELECT * FROM file_at_version('README.md', 'HEAD~1');
--   SELECT * FROM file_at_version('src/main.py', 'v1.0', '/path/to/repo');
CREATE OR REPLACE MACRO file_at_version(file, rev, repo := '.') AS TABLE
    SELECT
        file_path,
        ref,
        size_bytes,
        text AS content
    FROM git_read(git_uri(repo, file, rev));

-- file_changes: File-level summary of changes between two revisions.
-- Compares git trees using blob_hash to detect modifications even when
-- file sizes are unchanged. Like `git diff --stat`.
--
-- Examples:
--   SELECT * FROM file_changes('HEAD~1', 'HEAD');
--   SELECT * FROM file_changes('main', 'feature-branch', '/path/to/repo');
CREATE OR REPLACE MACRO file_changes(from_rev, to_rev, repo := '.') AS TABLE
    SELECT
        COALESCE(a.file_path, b.file_path) AS file_path,
        CASE
            WHEN a.file_path IS NULL THEN 'added'
            WHEN b.file_path IS NULL THEN 'deleted'
            ELSE 'modified'
        END AS status,
        a.size_bytes AS old_size,
        b.size_bytes AS new_size
    FROM git_tree(repo, from_rev) a
    FULL OUTER JOIN git_tree(repo, to_rev) b
        ON a.file_path = b.file_path
    WHERE a.file_path IS NULL
       OR b.file_path IS NULL
       OR a.blob_hash != b.blob_hash
    ORDER BY file_path;

-- file_diff: Line-level diff for a specific file between two revisions.
-- Parses diff content lines from read_git_diff into typed rows.
--
-- Examples:
--   SELECT * FROM file_diff('README.md', 'HEAD~1', 'HEAD');
--   SELECT * FROM file_diff('src/main.py', 'main', 'feature', '/path/to/repo');
CREATE OR REPLACE MACRO file_diff(file, from_rev, to_rev, repo := '.') AS TABLE
    WITH raw_diff AS (
        SELECT diff_text
        FROM read_git_diff(
            git_uri(repo, file, from_rev),
            git_uri(repo, file, to_rev)
        )
    ),
    lines AS (
        SELECT unnest(string_split(diff_text, chr(10))) AS line
        FROM raw_diff
    )
    SELECT
        row_number() OVER () AS seq,
        CASE
            WHEN starts_with(line, '+') THEN 'ADDED'
            WHEN starts_with(line, '-') THEN 'REMOVED'
            ELSE 'CONTEXT'
        END AS line_type,
        line[2:] AS content
    FROM lines
    WHERE length(line) > 0;

-- working_tree_status: Detect untracked and deleted files in the working tree.
-- Compares tracked files at HEAD against filesystem via glob(). Cannot detect
-- content modifications — only structural changes (files present or absent).
-- Note: gitignored files will appear as 'untracked'.
--
-- Examples:
--   SELECT * FROM working_tree_status();
--   SELECT * FROM working_tree_status('/path/to/repo');
CREATE OR REPLACE MACRO working_tree_status(repo := '.') AS TABLE
    WITH
        tracked AS (
            SELECT file_path
            FROM git_tree(repo, 'HEAD')
            WHERE kind = 'file'
        ),
        on_disk AS (
            SELECT replace(file, repo || '/', '') AS file_path
            FROM glob(repo || '/**')
            WHERE replace(file, repo || '/', '') <> '.git'
              AND NOT starts_with(replace(file, repo || '/', ''), '.git/')
        )
    SELECT
        COALESCE(t.file_path, d.file_path) AS file_path,
        CASE
            WHEN t.file_path IS NULL THEN 'untracked'
            WHEN d.file_path IS NULL THEN 'deleted'
        END AS status
    FROM tracked t
    FULL OUTER JOIN on_disk d
        ON t.file_path = d.file_path
    WHERE t.file_path IS NULL OR d.file_path IS NULL
    ORDER BY status, file_path;

;
-- conversations.sql: DuckDB macros for analyzing Claude Code conversation logs
--
-- Self-contained: creates raw_conversations if it does not already exist.
-- Reads JSONL from getvariable('conversations_root') || '/*/*.jsonl'.
-- All objects are CREATE OR REPLACE / CREATE TABLE IF NOT EXISTS for idempotency.
-- See docs/vision/CONVERSATION_SCHEMA_DESIGN.md for design details.

-- Bootstrap: Create raw_conversations table.
-- Uses query() for conditional dispatch: loads JSONL if files exist,
-- otherwise creates an empty table with the expected schema.
SET VARIABLE _has_conversations = (SELECT count(*) > 0 FROM glob(
    getvariable('conversations_root') || '/*/*.jsonl'
));
CREATE TABLE IF NOT EXISTS raw_conversations AS
SELECT * REPLACE (CAST(timestamp AS TIMESTAMP) AS timestamp) FROM query(
    CASE WHEN getvariable('_has_conversations')
    THEN 'SELECT *, filename AS _source_file FROM read_json_auto(
        ''' || getvariable('conversations_root') || '/*/*.jsonl'',
        union_by_name=true, maximum_object_size=33554432, filename=true,
        ignore_errors=true
    )'
    ELSE 'SELECT NULL::VARCHAR AS uuid, NULL::VARCHAR AS sessionId,
          NULL::VARCHAR AS type,
          NULL::STRUCT(role VARCHAR, content JSON, model VARCHAR, id VARCHAR, stop_reason VARCHAR, usage STRUCT(input_tokens BIGINT, output_tokens BIGINT, cache_creation_input_tokens BIGINT, cache_read_input_tokens BIGINT)) AS message,
          NULL::TIMESTAMP AS timestamp, NULL::VARCHAR AS requestId,
          NULL::VARCHAR AS slug, NULL::VARCHAR AS version,
          NULL::VARCHAR AS gitBranch, NULL::VARCHAR AS cwd,
          NULL::BOOLEAN AS isSidechain, NULL::BOOLEAN AS isMeta,
          NULL::VARCHAR AS parentUuid, NULL::VARCHAR AS _source_file
          WHERE false'
    END
);

-- 1. LOADING MACRO
CREATE OR REPLACE MACRO load_conversations(path) AS TABLE
    SELECT *, filename AS _source_file
    FROM read_json_auto(
        path, union_by_name=true, maximum_object_size=33554432, filename=true
    );

-- 2a. SESSIONS - One row per session with metadata
CREATE OR REPLACE MACRO sessions() AS TABLE
    SELECT
        sessionId AS session_id,
        regexp_extract(_source_file, '.claude/projects/([^/]+)/', 1) AS project_dir,
        last(slug ORDER BY timestamp) FILTER (WHERE slug IS NOT NULL) AS slug,
        last(version ORDER BY timestamp) FILTER (WHERE version IS NOT NULL) AS version,
        last(gitBranch ORDER BY timestamp) FILTER (WHERE gitBranch IS NOT NULL) AS git_branch,
        last(cwd ORDER BY timestamp) FILTER (WHERE cwd IS NOT NULL) AS working_dir,
        min(timestamp) AS started_at,
        max(timestamp) AS ended_at,
        age(max(timestamp), min(timestamp)) AS duration,
        count(*) FILTER (WHERE type = 'user') AS user_messages,
        count(*) FILTER (WHERE type = 'assistant') AS assistant_messages,
        count(*) FILTER (WHERE type = 'progress') AS progress_events,
        count(*) FILTER (WHERE type = 'system') AS system_events,
        count(*) AS total_records,
        any_value(_source_file) AS source_file
    FROM raw_conversations
    WHERE sessionId IS NOT NULL
    GROUP BY sessionId,
             regexp_extract(_source_file, '.claude/projects/([^/]+)/', 1);

-- 2b. MESSAGES - Flattened user + assistant messages
CREATE OR REPLACE MACRO messages() AS TABLE
    SELECT
        r.uuid AS message_id,
        r.sessionId AS session_id,
        r.parentUuid AS parent_id,
        r.type AS record_type,
        r.message.role AS role,
        r.message.content AS content,
        r.message.model AS model,
        r.message.id AS api_message_id,
        r.message.stop_reason AS stop_reason,
        r.requestId AS request_id,
        r.slug, r.version,
        r.gitBranch AS git_branch,
        r.cwd AS working_dir,
        r.isSidechain AS is_sidechain,
        r.isMeta AS is_meta,
        r.message.usage.input_tokens AS input_tokens,
        r.message.usage.output_tokens AS output_tokens,
        r.message.usage.cache_creation_input_tokens AS cache_creation_tokens,
        r.message.usage.cache_read_input_tokens AS cache_read_tokens,
        r.timestamp AS created_at,
        r._source_file AS source_file
    FROM raw_conversations r
    WHERE r.type IN ('user', 'assistant');

-- 2c. CONTENT BLOCKS - Unnested assistant message content
-- Key pattern: LATERAL UNNEST(CAST(content AS JSON[])) turns JSON array into rows
-- CTE filters first to prevent CAST errors on non-array content
CREATE OR REPLACE MACRO content_blocks() AS TABLE
    WITH array_messages AS (
        SELECT uuid, sessionId, slug, timestamp, requestId, message, _source_file
        FROM raw_conversations
        WHERE type = 'assistant'
          AND message.content IS NOT NULL
          AND json_type(message.content) = 'ARRAY'
    )
    SELECT
        r.uuid AS message_id,
        r.sessionId AS session_id,
        r.slug, r.timestamp AS created_at,
        r.requestId AS request_id,
        r.message.model AS model,
        b.block,
        b.block ->> 'type' AS block_type,
        b.block ->> 'text' AS text_content,
        b.block ->> 'thinking' AS thinking_content,
        b.block ->> 'name' AS tool_name,
        b.block ->> 'id' AS tool_use_id,
        b.block -> 'input' AS tool_input,
        r._source_file AS source_file
    FROM array_messages r,
         LATERAL UNNEST(CAST(r.message.content AS JSON[])) AS b(block);

-- 2d. TOOL CALLS - Extracted tool_use blocks with convenience columns
CREATE OR REPLACE MACRO tool_calls() AS TABLE
    SELECT
        cb.tool_use_id, cb.message_id, cb.session_id,
        cb.slug, cb.model, cb.created_at, cb.tool_name,
        cb.tool_input AS input,
        cb.tool_input ->> 'command' AS bash_command,
        COALESCE(cb.tool_input ->> 'file_path', cb.tool_input ->> 'path') AS file_path,
        cb.tool_input ->> 'pattern' AS grep_pattern,
        cb.source_file
    FROM content_blocks() cb
    WHERE cb.block_type = 'tool_use';

-- 2e. TOOL RESULTS - Matched tool_result blocks from user messages
-- Join: tool_calls.tool_use_id = tool_results.tool_use_id
CREATE OR REPLACE MACRO tool_results() AS TABLE
    WITH user_array_messages AS (
        SELECT uuid, sessionId, timestamp, message, _source_file
        FROM raw_conversations
        WHERE type = 'user'
          AND message.content IS NOT NULL
          AND json_type(message.content) = 'ARRAY'
    )
    SELECT
        r.uuid AS message_id,
        r.sessionId AS session_id,
        r.timestamp AS created_at,
        b.block ->> 'tool_use_id' AS tool_use_id,
        b.block ->> 'content' AS result_content,
        CAST(b.block ->> 'is_error' AS BOOLEAN) AS is_error,
        r._source_file AS source_file
    FROM user_array_messages r,
         LATERAL UNNEST(CAST(r.message.content AS JSON[])) AS b(block)
    WHERE b.block ->> 'type' = 'tool_result';

-- 2f. TOKEN USAGE - Per-message token consumption with cache metrics
-- WARNING: Deduplicate on request_id for accurate totals (chunks share usage)
CREATE OR REPLACE MACRO token_usage() AS TABLE
    SELECT
        m.message_id, m.session_id, m.request_id,
        m.model, m.created_at, m.slug,
        m.input_tokens, m.output_tokens,
        m.cache_creation_tokens, m.cache_read_tokens,
        COALESCE(m.input_tokens,0) + COALESCE(m.cache_creation_tokens,0)
            + COALESCE(m.cache_read_tokens,0) AS total_input_tokens,
        COALESCE(m.input_tokens,0) + COALESCE(m.output_tokens,0)
            + COALESCE(m.cache_creation_tokens,0)
            + COALESCE(m.cache_read_tokens,0) AS total_tokens,
        CASE WHEN COALESCE(m.input_tokens,0) + COALESCE(m.cache_creation_tokens,0)
                  + COALESCE(m.cache_read_tokens,0) > 0
             THEN COALESCE(m.cache_read_tokens,0)::FLOAT
                  / (COALESCE(m.input_tokens,0) + COALESCE(m.cache_creation_tokens,0)
                     + COALESCE(m.cache_read_tokens,0))
             ELSE NULL END AS cache_hit_rate,
        m.source_file
    FROM messages() m
    WHERE m.role = 'assistant' AND m.input_tokens IS NOT NULL;

-- 3a. TOOL FREQUENCY - Tool usage counts by project/session/tool
CREATE OR REPLACE MACRO tool_frequency() AS TABLE
    SELECT
        regexp_extract(tc.source_file, '.claude/projects/([^/]+)/', 1) AS project_dir,
        tc.session_id, tc.slug, tc.tool_name,
        count(*) AS call_count,
        min(tc.created_at) AS first_used,
        max(tc.created_at) AS last_used
    FROM tool_calls() tc GROUP BY ALL;

-- 3b. BASH COMMANDS - Parsed bash command analysis with categories
-- Categories: git_read, git_write, github_cli, build_tools, runtime_exec,
--   file_search, file_read, filesystem, text_processing, network, other
-- replaceable_by: duck_tails, sitting_duck, read_lines, duckdb_sql
CREATE OR REPLACE MACRO bash_commands() AS TABLE
    SELECT
        tc.tool_use_id, tc.message_id, tc.session_id,
        tc.slug, tc.created_at,
        tc.bash_command AS command,
        regexp_extract(trim(tc.bash_command), '^(\S+)', 1) AS leading_command,
        CASE WHEN trim(tc.bash_command) LIKE 'git %'
             THEN regexp_extract(trim(tc.bash_command), '^git\s+(\S+)', 1)
             ELSE NULL END AS git_subcommand,
        CASE WHEN trim(tc.bash_command) LIKE 'gh %'
             THEN regexp_extract(trim(tc.bash_command), '^gh\s+(\S+\s*\S*)', 1)
             ELSE NULL END AS gh_subcommand,
        CASE
            WHEN trim(tc.bash_command) LIKE 'git diff%'
              OR trim(tc.bash_command) LIKE 'git log%'
              OR trim(tc.bash_command) LIKE 'git status%'
              OR trim(tc.bash_command) LIKE 'git show%'
              OR trim(tc.bash_command) LIKE 'git rev-parse%'
              OR trim(tc.bash_command) LIKE 'git branch%'
              OR trim(tc.bash_command) LIKE 'git remote%'
              OR trim(tc.bash_command) LIKE 'git config%' THEN 'git_read'
            WHEN trim(tc.bash_command) LIKE 'git %' THEN 'git_write'
            WHEN trim(tc.bash_command) LIKE 'gh %' THEN 'github_cli'
            WHEN trim(tc.bash_command) LIKE 'cargo %'
              OR trim(tc.bash_command) LIKE 'make%'
              OR trim(tc.bash_command) LIKE 'npm %'
              OR trim(tc.bash_command) LIKE 'yarn %'
              OR trim(tc.bash_command) LIKE 'pip %'
              OR trim(tc.bash_command) LIKE 'pip3 %'
              OR trim(tc.bash_command) LIKE 'uv %'
              OR trim(tc.bash_command) LIKE 'cmake%' THEN 'build_tools'
            WHEN trim(tc.bash_command) LIKE 'python%'
              OR trim(tc.bash_command) LIKE 'node %'
              OR trim(tc.bash_command) LIKE 'duckdb%'
              OR trim(tc.bash_command) LIKE 'ruby %'
              OR trim(tc.bash_command) LIKE 'java %'
              OR trim(tc.bash_command) LIKE 'go %' THEN 'runtime_exec'
            WHEN trim(tc.bash_command) LIKE 'grep %'
              OR trim(tc.bash_command) LIKE 'rg %'
              OR trim(tc.bash_command) LIKE 'find %'
              OR trim(tc.bash_command) LIKE 'fd %'
              OR trim(tc.bash_command) LIKE 'ag %' THEN 'file_search'
            WHEN trim(tc.bash_command) LIKE 'cat %'
              OR trim(tc.bash_command) LIKE 'head %'
              OR trim(tc.bash_command) LIKE 'tail %'
              OR trim(tc.bash_command) LIKE 'less %'
              OR trim(tc.bash_command) LIKE 'bat %'
              OR trim(tc.bash_command) LIKE 'sed -n%' THEN 'file_read'
            WHEN trim(tc.bash_command) LIKE 'ls%'
              OR trim(tc.bash_command) LIKE 'mkdir%'
              OR trim(tc.bash_command) LIKE 'rm %'
              OR trim(tc.bash_command) LIKE 'cp %'
              OR trim(tc.bash_command) LIKE 'mv %'
              OR trim(tc.bash_command) LIKE 'chmod%'
              OR trim(tc.bash_command) LIKE 'touch %' THEN 'filesystem'
            WHEN trim(tc.bash_command) LIKE 'wc %'
              OR trim(tc.bash_command) LIKE 'sort %'
              OR trim(tc.bash_command) LIKE 'uniq %'
              OR trim(tc.bash_command) LIKE 'awk %'
              OR trim(tc.bash_command) LIKE 'cut %'
              OR trim(tc.bash_command) LIKE 'jq %' THEN 'text_processing'
            WHEN trim(tc.bash_command) LIKE 'curl %'
              OR trim(tc.bash_command) LIKE 'wget %'
              OR trim(tc.bash_command) LIKE 'ssh %'
              OR trim(tc.bash_command) LIKE 'scp %' THEN 'network'
            ELSE 'other'
        END AS category,
        CASE
            WHEN trim(tc.bash_command) LIKE 'git diff%'
              OR trim(tc.bash_command) LIKE 'git log%'
              OR trim(tc.bash_command) LIKE 'git status%'
              OR trim(tc.bash_command) LIKE 'git show%'
              OR trim(tc.bash_command) LIKE 'git rev-parse%'
              OR trim(tc.bash_command) LIKE 'git branch%' THEN 'duck_tails'
            WHEN trim(tc.bash_command) LIKE 'grep %'
              OR trim(tc.bash_command) LIKE 'rg %'
              OR trim(tc.bash_command) LIKE 'find %'
              OR trim(tc.bash_command) LIKE 'fd %' THEN 'sitting_duck'
            WHEN trim(tc.bash_command) LIKE 'cat %'
              OR trim(tc.bash_command) LIKE 'head %'
              OR trim(tc.bash_command) LIKE 'tail %' THEN 'read_lines'
            WHEN trim(tc.bash_command) LIKE 'wc %'
              OR trim(tc.bash_command) LIKE 'sort %'
              OR trim(tc.bash_command) LIKE 'awk %' THEN 'duckdb_sql'
            ELSE NULL
        END AS replaceable_by,
        tc.source_file
    FROM tool_calls() tc
    WHERE tc.tool_name = 'Bash' AND tc.bash_command IS NOT NULL;

-- 3c. SESSION SUMMARY - Dashboard view with all stats per session
CREATE OR REPLACE MACRO session_summary() AS TABLE
    SELECT
        s.session_id, s.project_dir, s.slug, s.version,
        s.git_branch, s.started_at, s.ended_at, s.duration,
        s.user_messages, s.assistant_messages, s.total_records,
        COALESCE(tc.total_tool_calls, 0) AS total_tool_calls,
        COALESCE(tc.distinct_tools, 0) AS distinct_tools_used,
        tc.top_tool,
        COALESCE(tk.total_input, 0) AS total_input_tokens,
        COALESCE(tk.total_output, 0) AS total_output_tokens,
        COALESCE(tk.total_tokens, 0) AS total_tokens,
        tk.avg_cache_hit_rate,
        COALESCE(bc.bash_calls, 0) AS bash_calls,
        COALESCE(bc.replaceable_calls, 0) AS bash_replaceable_calls
    FROM sessions() s
    LEFT JOIN (
        SELECT session_id, count(*) AS total_tool_calls,
               count(DISTINCT tool_name) AS distinct_tools,
               mode(tool_name) AS top_tool
        FROM tool_calls() GROUP BY session_id
    ) tc ON tc.session_id = s.session_id
    LEFT JOIN (
        SELECT session_id, sum(input_tokens) AS total_input,
               sum(output_tokens) AS total_output,
               sum(total_tokens) AS total_tokens,
               avg(cache_hit_rate) AS avg_cache_hit_rate
        FROM (
            SELECT DISTINCT ON (request_id) session_id, request_id,
                input_tokens, output_tokens, total_tokens, cache_hit_rate
            FROM token_usage()
            ORDER BY request_id, output_tokens DESC NULLS LAST
        ) GROUP BY session_id
    ) tk ON tk.session_id = s.session_id
    LEFT JOIN (
        SELECT session_id, count(*) AS bash_calls,
               count(*) FILTER (WHERE replaceable_by IS NOT NULL) AS replaceable_calls
        FROM bash_commands() GROUP BY session_id
    ) bc ON bc.session_id = s.session_id;

-- 3d. MODEL USAGE - Token consumption by model
CREATE OR REPLACE MACRO model_usage() AS TABLE
    SELECT model,
        count(DISTINCT session_id) AS sessions,
        count(DISTINCT request_id) AS api_calls,
        sum(input_tokens) AS total_input_tokens,
        sum(output_tokens) AS total_output_tokens,
        sum(total_tokens) AS total_tokens,
        avg(cache_hit_rate) AS avg_cache_hit_rate
    FROM (
        SELECT DISTINCT ON (request_id) session_id, request_id, model,
            input_tokens, output_tokens, total_tokens, cache_hit_rate
        FROM token_usage() WHERE model IS NOT NULL
        ORDER BY request_id, output_tokens DESC NULLS LAST
    ) GROUP BY model ORDER BY total_tokens DESC;

-- 4a. SEARCH MESSAGES - Full-text search across conversation content
-- NOTE: Uses json_extract_string() instead of ->> in UNION ALL to avoid
-- a DuckDB macro parsing issue with the ->> operator in UNION context.
CREATE OR REPLACE MACRO search_messages(search_term) AS TABLE
    SELECT uuid AS message_id, sessionId AS session_id, slug,
           'user' AS role, CAST(message.content AS VARCHAR) AS content,
           timestamp AS created_at
    FROM raw_conversations
    WHERE type = 'user'
      AND CAST(message.content AS VARCHAR) ILIKE '%' || search_term || '%'
      AND json_type(message.content) != 'ARRAY'
    UNION ALL
    SELECT r.uuid, r.sessionId, r.slug,
           'assistant', json_extract_string(b.block, '$.text'), r.timestamp
    FROM (SELECT uuid, sessionId, slug, timestamp, message
          FROM raw_conversations
          WHERE type = 'assistant'
            AND message.content IS NOT NULL
            AND json_type(message.content) = 'ARRAY') r,
         LATERAL UNNEST(CAST(r.message.content AS JSON[])) AS b(block)
    WHERE json_extract_string(b.block, '$.type') = 'text'
      AND json_extract_string(b.block, '$.text') ILIKE '%' || search_term || '%';

-- 4b. SEARCH TOOL INPUTS - Search within tool call parameters
CREATE OR REPLACE MACRO search_tool_inputs(search_term) AS TABLE
    SELECT tc.tool_use_id, tc.session_id, tc.slug, tc.tool_name,
           tc.bash_command, tc.file_path, tc.grep_pattern,
           CAST(tc.input AS VARCHAR) AS input_text, tc.created_at
    FROM tool_calls() tc
    WHERE CAST(tc.input AS VARCHAR) ILIKE '%' || search_term || '%';

;
-- Fledgling: Documentation Intelligence Macros (duckdb_markdown)
--
-- Structured access to markdown documentation. The documentation
-- counterpart to sitting_duck's source code analysis.

-- doc_outline: Get the structural outline (table of contents) of markdown files.
-- Lets the agent decide what to read before committing tokens.
--
-- Examples:
--   SELECT * FROM doc_outline('README.md');
--   SELECT * FROM doc_outline('docs/**/*.md');
--   SELECT * FROM doc_outline('docs/**/*.md', 2);
CREATE OR REPLACE MACRO doc_outline(file_pattern, max_lvl := 3) AS TABLE
    SELECT
        file_path,
        section_id,
        section_path,
        level,
        title,
        start_line,
        end_line
    FROM read_markdown_sections(
        file_pattern,
        include_content := false,
        max_level := max_lvl,
        include_filepath := true
    )
    ORDER BY file_path, start_line;

-- read_doc_section: Read a specific section from a markdown file.
-- Uses section ID or path prefix matching for flexible section access.
-- Parameter named target_id (not section_id) to avoid shadowing the
-- column s.section_id in the WHERE clause.
--
-- Examples:
--   SELECT * FROM read_doc_section('README.md', 'installation');
--   SELECT * FROM read_doc_section('docs/guide.md', 'getting-started');
CREATE OR REPLACE MACRO read_doc_section(file_path, target_id) AS TABLE
    SELECT
        s.section_id,
        s.title,
        s.level,
        s.content,
        s.start_line,
        s.end_line
    FROM read_markdown_sections(
        file_path,
        content_mode := 'full',
        include_content := true,
        include_filepath := false
    ) s
    WHERE s.section_id = target_id
       OR s.section_path LIKE '%/' || target_id
       OR s.section_path LIKE target_id || '/%';

-- find_code_examples: Extract code blocks from documentation.
-- Optionally filter by language.
--
-- Examples:
--   SELECT * FROM find_code_examples('docs/**/*.md');
--   SELECT * FROM find_code_examples('README.md', 'sql');
CREATE OR REPLACE MACRO find_code_examples(file_pattern, lang := NULL) AS TABLE
    SELECT
        s.file_path,
        s.section_id AS section,
        s.title AS section_title,
        cb.language,
        cb.code,
        cb.line_number
    FROM read_markdown_sections(
        file_pattern,
        include_content := true,
        include_filepath := true
    ) s,
    LATERAL (
        SELECT u.language, u.code, u.line_number
        FROM (SELECT UNNEST(md_extract_code_blocks(s.content)) AS u)
    ) cb
    WHERE lang IS NULL OR cb.language = lang;

-- doc_stats: Get statistics about markdown documentation files.
--
-- Examples:
--   SELECT * FROM doc_stats('docs/**/*.md');
CREATE OR REPLACE MACRO doc_stats(file_pattern) AS TABLE
    SELECT
        file_path,
        md_stats(content).word_count AS word_count,
        md_stats(content).heading_count AS heading_count,
        md_stats(content).code_block_count AS code_block_count,
        md_stats(content).link_count AS link_count,
        md_stats(content).reading_time_minutes AS reading_time_min
    FROM read_markdown(file_pattern, include_filepath := true)
    ORDER BY word_count DESC;

;
-- Fledgling: Diagnostics Module (dr_fledgling)
--
-- Self-contained: materializes extension info at load time (before sandbox
-- lockdown blocks access to the extensions directory). The dr_fledgling()
-- macro reads from the materialized table at call time.

-- Bootstrap: snapshot loaded fledgling extensions before lockdown.
-- duckdb_extensions() requires filesystem access to the extensions dir,
-- which is blocked after enable_external_access = false.
CREATE TABLE IF NOT EXISTS _fledgling_extensions AS
SELECT array_to_string(list(extension_name ORDER BY extension_name), ', ') AS extensions
FROM duckdb_extensions() WHERE installed AND loaded
AND extension_name IN ('duckdb_mcp','read_lines','sitting_duck','markdown','duck_tails');

-- dr_fledgling: Runtime diagnostic summary.
-- Returns key-value pairs: version, profile, root, modules, extensions.
--
-- Examples:
--   SELECT * FROM dr_fledgling();
CREATE OR REPLACE MACRO dr_fledgling() AS TABLE
    SELECT * FROM (VALUES
        ('version',    getvariable('fledgling_version')),
        ('profile',    getvariable('fledgling_profile')),
        ('root',       getvariable('session_root')),
        ('modules',    array_to_string(getvariable('fledgling_modules'), ', ')),
        ('extensions', (SELECT extensions FROM _fledgling_extensions))
    ) AS t(key, value);

;
-- Fledgling: Help System Macro
--
-- Provides agent-accessible skill documentation from a materialized
-- table. Bootstraps _help_sections from the skill guide on load.

-- Bootstrap: Materialize _help_sections from the skill guide.
-- Path priority: _help_path variable > SKILL.md in current directory.
-- The installer sets _help_path to '.fledgling-help.md'.
-- init-fledgling-base.sql sets it to 'SKILL.md' (or leaves default).
CREATE TABLE IF NOT EXISTS _help_sections AS
SELECT section_id, section_path, level, title, content, start_line, end_line
FROM read_markdown_sections(
    COALESCE(getvariable('_help_path'), 'SKILL.md'),
    content_mode := 'full',
    include_content := true, include_filepath := false
);

-- help: Browse the Fledgling skill guide.
-- With no arguments, returns an outline (section IDs and titles).
-- With a section ID, returns matching sections with full content.
-- Supports path prefix matching so parent IDs return children.
--
-- Examples:
--   SELECT * FROM help();
--   SELECT * FROM help('workflows');
--   SELECT * FROM help('code-intelligence');
CREATE OR REPLACE MACRO help(target_id := NULL) AS TABLE
    SELECT
        section_id,
        title,
        level,
        CASE WHEN target_id IS NOT NULL THEN content END AS content
    FROM _help_sections
    WHERE (target_id IS NULL AND level <= 3)
       OR section_id = target_id
       OR section_path LIKE '%/' || target_id
       OR section_path LIKE '%/' || target_id || '/%'
    ORDER BY start_line;

;
-- Fledgling: Source Retrieval Macros (read_lines)
--
-- Thin wrappers around read_lines that provide convenient interfaces
-- for the common file-reading patterns agents use most.
--
-- NOTE: sitting_duck#22 (read_lines shadowing) is fixed in DuckDB 1.4.4+.
-- The DROP MACRO TABLE workaround is no longer needed.

-- read_source: Read lines from a file with optional line selection and filtering.
-- This is the primary replacement for cat/head/tail bash commands.
-- Use match to filter lines by case-insensitive substring match.
--
-- Examples:
--   SELECT * FROM read_source('src/main.py');
--   SELECT * FROM read_source('src/main.py', '10-20');
--   SELECT * FROM read_source('src/main.py', '42 +/-5');
--   SELECT * FROM read_source('src/main.py', match := 'import');
CREATE OR REPLACE MACRO read_source(file_path, lines := NULL, ctx := 0, match := NULL) AS TABLE
    SELECT line_number, content
    FROM (
        SELECT
            line_number,
            content,
            max(CASE WHEN content ILIKE '%' || match || '%' THEN 1 ELSE 0 END)
                OVER (
                    ORDER BY line_number
                    ROWS BETWEEN ctx PRECEDING AND ctx FOLLOWING
                ) AS near_match
        FROM read_lines(file_path, lines, context := ctx)
    )
    WHERE match IS NULL OR near_match > 0;

-- read_source_batch: Like read_source but includes file_path column
-- for multi-file batch reads via glob patterns.
--
-- Examples:
--   SELECT * FROM read_source_batch('src/**/*.py', '1-10');
CREATE OR REPLACE MACRO read_source_batch(file_pattern, lines := NULL, ctx := 0) AS TABLE
    SELECT
        file_path,
        line_number,
        content
    FROM read_lines(file_pattern, lines, context := ctx);

-- read_context: Read lines centered around a specific line number.
-- Optimized for error investigation — show context around a location.
--
-- Examples:
--   SELECT * FROM read_context('src/main.py', 42);
--   SELECT * FROM read_context('src/main.py', 42, 10);
CREATE OR REPLACE MACRO read_context(file_path, center_line, ctx := 5) AS TABLE
    SELECT
        line_number,
        content,
        line_number = center_line AS is_center
    FROM read_lines(file_path, center_line, context := ctx);

-- file_line_count: Get line counts for files matching a pattern.
--
-- Examples:
--   SELECT * FROM file_line_count('src/**/*.py');
CREATE OR REPLACE MACRO file_line_count(file_pattern) AS TABLE
    SELECT
        file_path,
        max(line_number) AS line_count
    FROM read_lines(file_pattern)
    GROUP BY file_path
    ORDER BY line_count DESC;

-- list_files: List files matching a pattern.
-- Filesystem mode uses glob syntax; git mode uses SQL LIKE syntax.
-- Uses query() for dynamic dispatch so git functions (duck_tails) are only
-- resolved at runtime when commit is provided.
--
-- Examples:
--   SELECT * FROM list_files('src/**/*.py');
--   SELECT * FROM list_files('sql/%', 'HEAD');
CREATE OR REPLACE MACRO list_files(pattern, commit := NULL) AS TABLE
    SELECT * FROM query(
        CASE WHEN commit IS NULL
             THEN 'SELECT file AS file_path FROM glob(''' || replace(pattern, '''', '''''') || ''') ORDER BY file_path'
             ELSE 'SELECT file_path FROM git_tree(''.'', ''' || replace(commit, '''', '''''') || ''') WHERE file_path LIKE ''' || replace(pattern, '''', '''''') || ''' ORDER BY file_path'
        END
    );

-- project_overview: Summarize project contents by file type.
-- Groups files by extension and maps to language names, giving a quick
-- overview of what a project contains. Filters out .git, .venv,
-- node_modules, __pycache__, and other dependency/build directories.
--
-- Examples:
--   SELECT * FROM project_overview('/path/to/project');
--   SELECT * FROM project_overview('.');
CREATE OR REPLACE MACRO project_overview(root := '.') AS TABLE
    SELECT
        CASE extension
            WHEN 'py' THEN 'Python'
            WHEN 'pyi' THEN 'Python'
            WHEN 'js' THEN 'JavaScript'
            WHEN 'jsx' THEN 'JavaScript'
            WHEN 'mjs' THEN 'JavaScript'
            WHEN 'ts' THEN 'TypeScript'
            WHEN 'tsx' THEN 'TypeScript'
            WHEN 'sql' THEN 'SQL'
            WHEN 'rs' THEN 'Rust'
            WHEN 'go' THEN 'Go'
            WHEN 'java' THEN 'Java'
            WHEN 'rb' THEN 'Ruby'
            WHEN 'sh' THEN 'Shell'
            WHEN 'bash' THEN 'Shell'
            WHEN 'zsh' THEN 'Shell'
            WHEN 'md' THEN 'Markdown'
            WHEN 'json' THEN 'JSON'
            WHEN 'yaml' THEN 'YAML'
            WHEN 'yml' THEN 'YAML'
            WHEN 'toml' THEN 'TOML'
            WHEN 'html' THEN 'HTML'
            WHEN 'css' THEN 'CSS'
            WHEN 'c' THEN 'C'
            WHEN 'cpp' THEN 'C++'
            WHEN 'cc' THEN 'C++'
            WHEN 'h' THEN 'C/C++'
            WHEN 'hpp' THEN 'C/C++'
            WHEN 'txt' THEN 'Text'
            WHEN 'xml' THEN 'XML'
            WHEN '' THEN '(other)'
            ELSE extension
        END AS language,
        extension,
        count(*) AS file_count
    FROM (
        SELECT
            lower(regexp_extract(file_path, '\.([^./]+)$', 1)) AS extension
        FROM list_files(rtrim(root, '/') || '/**/*')
        WHERE file_path NOT LIKE '%/.git/%'
          AND file_path NOT LIKE '%/.venv/%'
          AND file_path NOT LIKE '%/venv/%'
          AND file_path NOT LIKE '%/node_modules/%'
          AND file_path NOT LIKE '%/__pycache__/%'
          AND file_path NOT LIKE '%/.mypy_cache/%'
          AND file_path NOT LIKE '%/.pytest_cache/%'
          AND file_path NOT LIKE '%/.tox/%'
          AND file_path NOT LIKE '%/dist/%'
          AND file_path NOT LIKE '%/build/%'
          AND file_path NOT LIKE '%/.eggs/%'
          AND file_path NOT LIKE '%/*.egg-info/%'
    )
    GROUP BY ALL
    ORDER BY file_count DESC;

-- read_as_table: Preview structured data files (CSV, JSON) as tables.
-- Uses query() for dynamic dispatch between read_csv_auto and read_json_auto
-- based on file extension. Avoids query_table() which conflicts with Python's
-- json module in DuckDB's replacement scan.
--
-- Examples:
--   SELECT * FROM read_as_table('data.csv');
--   SELECT * FROM read_as_table('data.json', 10);
CREATE OR REPLACE MACRO read_as_table(file_path, lim := 100) AS TABLE
    SELECT * FROM query(
        CASE WHEN file_path LIKE '%.json' OR file_path LIKE '%.jsonl'
             THEN 'SELECT * FROM read_json_auto(''' || replace(file_path, '''', '''''') || ''') LIMIT ' || CAST(lim AS VARCHAR)
             ELSE 'SELECT * FROM read_csv_auto(''' || replace(file_path, '''', '''''') || ''') LIMIT ' || CAST(lim AS VARCHAR)
        END
    );

;
-- Fledgling: Structural Analysis Macros (sitting_duck + duck_tails)
--
-- Cross-tier macros combining AST analysis with git repository state.
-- Must load AFTER both sitting_duck and duck_tails extensions.

-- structural_diff: Compare definitions between two revisions of a file.
-- Shows which functions/classes were added, removed, or modified, with
-- complexity change signals (descendant_count, children_count).
--
-- Uses read_ast with git:// URIs to parse both revisions. Identity is
-- (name, semantic_type) — line number shifts from unrelated edits do not
-- count as modifications. Change detection uses descendant_count and
-- children_count from the AST, which reflect structural complexity
-- independent of formatting.
--
-- Requires: sitting_duck with git:// URI support (sitting_duck#48).
--
-- Examples:
--   SELECT * FROM structural_diff('src/main.py', 'HEAD~1', 'HEAD');
--   SELECT * FROM structural_diff('lib/parser.py', 'main', 'feature-branch');
CREATE OR REPLACE MACRO structural_diff(file, from_rev, to_rev, repo := '.') AS TABLE
    WITH from_defs AS (
        SELECT
            name,
            semantic_type,
            semantic_type_to_string(semantic_type) AS kind,
            end_line - start_line + 1 AS line_count,
            descendant_count,
            children_count
        FROM read_ast(git_uri(repo, file, from_rev))
        WHERE is_definition(semantic_type)
          AND depth <= 2
          AND name != ''
    ),
    to_defs AS (
        SELECT
            name,
            semantic_type,
            semantic_type_to_string(semantic_type) AS kind,
            end_line - start_line + 1 AS line_count,
            descendant_count,
            children_count
        FROM read_ast(git_uri(repo, file, to_rev))
        WHERE is_definition(semantic_type)
          AND depth <= 2
          AND name != ''
    )
    SELECT
        COALESCE(t.name, f.name) AS name,
        COALESCE(t.kind, f.kind) AS kind,
        CASE
            WHEN f.name IS NULL THEN 'added'
            WHEN t.name IS NULL THEN 'removed'
            WHEN t.descendant_count != f.descendant_count
              OR t.children_count != f.children_count THEN 'modified'
            ELSE 'unchanged'
        END AS change,
        f.line_count AS old_lines,
        t.line_count AS new_lines,
        f.descendant_count AS old_complexity,
        t.descendant_count AS new_complexity,
        COALESCE(t.descendant_count::INT, 0)
            - COALESCE(f.descendant_count::INT, 0) AS complexity_delta
    FROM to_defs t
    FULL OUTER JOIN from_defs f
        ON t.name = f.name AND t.semantic_type = f.semantic_type
    WHERE change != 'unchanged'
    ORDER BY change, name;

-- changed_function_summary: Functions in files that changed between two revisions,
-- with complexity metrics. Answers "what functions should I review for this change?"
--
-- Uses file_changes (duck_tails) to identify modified/added files, then
-- read_ast to parse their current content and extract function metrics.
-- Sorted by cyclomatic complexity so the riskiest functions surface first.
--
-- Unlike structural_diff (which shows what changed within a function),
-- this shows all functions in changed files — a broader review surface.
--
-- The file_pattern parameter scopes which files to AST-parse (e.g. '**/*.py').
-- Only files matching BOTH the pattern AND the changed file list are included.
--
-- Examples:
--   SELECT * FROM changed_function_summary('HEAD~1', 'HEAD', '**/*.py');
--   SELECT * FROM changed_function_summary('main', 'feature', 'src/**/*.py');
CREATE OR REPLACE MACRO changed_function_summary(from_rev, to_rev, file_pattern, repo := '.') AS TABLE
    WITH changed AS (
        SELECT file_path, status
        FROM file_changes(from_rev, to_rev, repo)
        WHERE status IN ('added', 'modified')
    ),
    ast AS (
        SELECT * FROM read_ast(file_pattern)
    ),
    metrics AS (
        SELECT * FROM ast_function_metrics(ast)
    ),
    defs AS (
        SELECT
            file_path,
            name,
            semantic_type_to_string(semantic_type) AS kind,
            start_line,
            end_line - start_line + 1 AS lines
        FROM ast
        WHERE is_definition(semantic_type)
          AND depth <= 2
          AND name != ''
    )
    SELECT
        d.file_path,
        d.name,
        d.kind,
        d.lines,
        COALESCE(m.cyclomatic, 0) AS cyclomatic,
        c.status AS change_status
    FROM defs d
    JOIN changed c ON suffix(d.file_path, '/' || c.file_path)
                   OR d.file_path = c.file_path
    LEFT JOIN metrics m ON d.file_path = m.file_path AND d.name = m.name
    ORDER BY COALESCE(m.cyclomatic, 0) DESC, d.file_path, d.start_line;

;
-- Fledgling: Code Intelligence Tool Publications
--
-- Publishes 2 MCP tools for AST-based code analysis.
-- Macros are defined in sql/code.sql; this file only creates MCP bindings.
--
-- Embeds session_root at publish time (getvariable is not available
-- in MCP tool execution context). Must be loaded after sandbox.sql
-- and code.sql, with session_root already set.
--
-- Macros without tool publications (use via query tool):
--   find_calls, find_imports, complexity_hotspots, function_callers,
--   module_dependencies

SELECT mcp_publish_tool(
    'FindDefinitions',
    'AST-based definition search — not grep. Finds functions, classes, and variable definitions. Use name_pattern with SQL LIKE wildcards (%) to filter by name.',
    'SELECT * FROM find_definitions(
        _resolve($file_pattern),
        COALESCE(NULLIF($name_pattern, ''null''), ''%'')
    )',
    '{"file_pattern": {"type": "string", "description": "Glob pattern for files to search (e.g. src/**/*.py)"}, "name_pattern": {"type": "string", "description": "SQL LIKE pattern to filter by name (e.g. parse%). Default: % (all)"}}',
    '["file_pattern"]',
    'markdown'
);

SELECT mcp_publish_tool(
    'CodeStructure',
    'Top-level structural overview of source files: definitions with line counts. Good first step for unfamiliar code. For deeper analysis, use complexity_hotspots() and module_dependencies() via the query tool.',
    'SELECT * FROM code_structure(
        _resolve($file_pattern)
    )',
    '{"file_pattern": {"type": "string", "description": "Glob pattern for files to analyze (e.g. src/**/*.py)"}}',
    '["file_pattern"]',
    'markdown'
);

;
-- Fledgling: Git Repository Tool Publications
--
-- MCP tool publications for git repository state.
-- Wraps macros from sql/repo.sql and sql/structural.sql.
--
-- Embeds session_root at publish time (getvariable is not available
-- in MCP tool execution context). Must be loaded after sandbox.sql
-- and repo.sql, with session_root already set.
--
-- Macros without tool publications (use via query tool):
--   recent_changes, branch_list, tag_list, working_tree_status,
--   file_diff, structural_diff, changed_function_summary

SELECT mcp_publish_tool(
    'GitDiffSummary',
    'File-level summary of changes between two git revisions. Shows added, deleted, and modified files with sizes. For function-level analysis, use structural_diff() or changed_function_summary() via the query tool.',
    'SELECT * FROM file_changes(
        $from_rev,
        $to_rev,
        COALESCE(_resolve(NULLIF($path, ''null'')), ''.'')
    )',
    '{"from_rev": {"type": "string", "description": "Base revision (e.g. HEAD~1, main, commit hash)"}, "to_rev": {"type": "string", "description": "Target revision (e.g. HEAD, feature-branch)"}, "path": {"type": "string", "description": "Repository path (default: project root)"}}',
    '["from_rev", "to_rev"]',
    'markdown'
);

SELECT mcp_publish_tool(
    'GitShow',
    'Show file content at a specific git revision with metadata (path, ref, size). Replaces `git show rev:path`.',
    'SELECT * FROM file_at_version(
        $file,
        $rev,
        COALESCE(_resolve(NULLIF($path, ''null'')), ''.'')
    )',
    '{"file": {"type": "string", "description": "Repository-relative file path (e.g. README.md, sql/repo.sql)"}, "rev": {"type": "string", "description": "Git revision (e.g. HEAD, HEAD~1, main, v1.0, commit hash)"}, "path": {"type": "string", "description": "Repository path (default: project root)"}}',
    '["file", "rev"]',
    'json'
);

;
-- Fledgling: Conversation Intelligence Tool Publications
--
-- MCP tool publications for Claude Code conversation analysis.
-- Wraps macros from sql/conversations.sql.

SELECT mcp_publish_tool(
    'ChatSessions',
    'Browse Claude Code conversation sessions. Shows session metadata, duration, tool usage, and token consumption. Filter by project name or date range.',
    'SELECT session_id, project_dir, slug, git_branch,
            started_at, duration, user_messages,
            total_tool_calls, distinct_tools_used, top_tool,
            total_tokens, avg_cache_hit_rate
     FROM session_summary()
     WHERE (NULLIF($project, ''null'') IS NULL
            OR project_dir ILIKE ''%'' || NULLIF($project, ''null'') || ''%'')
       AND (NULLIF($days, ''null'') IS NULL
            OR started_at >= CURRENT_TIMESTAMP::TIMESTAMP - (NULLIF($days, ''null'') || '' days'')::INTERVAL)
     ORDER BY started_at DESC
     LIMIT COALESCE(TRY_CAST(NULLIF($limit, ''null'') AS INT), 20)',
    '{"project": {"type": "string", "description": "Substring match on project directory name (case-insensitive)"}, "days": {"type": "string", "description": "Only sessions from last N days"}, "limit": {"type": "string", "description": "Max rows returned (default 20)"}}',
    '[]',
    'markdown'
);

SELECT mcp_publish_tool(
    'ChatSearch',
    'Full-text search across Claude Code conversation messages. Finds matching text in both user and assistant messages. Filter by role, project, or date range.',
    'SELECT sm.session_id, sm.slug, sm.role,
            left(sm.content, 500) AS content_preview, sm.created_at
     FROM search_messages($query) sm
     LEFT JOIN sessions() s ON s.session_id = sm.session_id
     WHERE (NULLIF($role, ''null'') IS NULL
            OR sm.role = NULLIF($role, ''null''))
       AND (NULLIF($project, ''null'') IS NULL
            OR s.project_dir ILIKE ''%'' || NULLIF($project, ''null'') || ''%'')
       AND (NULLIF($days, ''null'') IS NULL
            OR sm.created_at >= CURRENT_TIMESTAMP::TIMESTAMP - (NULLIF($days, ''null'') || '' days'')::INTERVAL)
     ORDER BY sm.created_at DESC
     LIMIT COALESCE(TRY_CAST(NULLIF($limit, ''null'') AS INT), 20)',
    '{"query": {"type": "string", "description": "Search term (case-insensitive substring match)"}, "role": {"type": "string", "description": "Filter to user or assistant messages"}, "project": {"type": "string", "description": "Substring match on project directory name"}, "days": {"type": "string", "description": "Only messages from last N days"}, "limit": {"type": "string", "description": "Max rows returned (default 20)"}}',
    '["query"]',
    'markdown'
);

SELECT mcp_publish_tool(
    'ChatToolUsage',
    'Tool usage patterns across Claude Code sessions. Shows which tools are used most frequently, with session counts and date ranges. Filter by project, session, or date range.',
    'SELECT tf.tool_name,
            sum(tf.call_count) AS total_calls,
            count(DISTINCT tf.session_id) AS sessions,
            min(tf.first_used) AS first_used,
            max(tf.last_used) AS last_used
     FROM tool_frequency() tf
     LEFT JOIN sessions() s ON s.session_id = tf.session_id
     WHERE (NULLIF($project, ''null'') IS NULL
            OR s.project_dir ILIKE ''%'' || NULLIF($project, ''null'') || ''%'')
       AND (NULLIF($session_id, ''null'') IS NULL
            OR tf.session_id = NULLIF($session_id, ''null''))
       AND (NULLIF($days, ''null'') IS NULL
            OR tf.first_used >= CURRENT_TIMESTAMP::TIMESTAMP - (NULLIF($days, ''null'') || '' days'')::INTERVAL)
     GROUP BY tf.tool_name
     ORDER BY total_calls DESC
     LIMIT COALESCE(TRY_CAST(NULLIF($limit, ''null'') AS INT), 50)',
    '{"project": {"type": "string", "description": "Substring match on project directory name"}, "session_id": {"type": "string", "description": "Filter to a single session UUID"}, "days": {"type": "string", "description": "Only usage from last N days"}, "limit": {"type": "string", "description": "Max rows returned (default 50)"}}',
    '[]',
    'markdown'
);

SELECT mcp_publish_tool(
    'ChatDetail',
    'Deep view of a single Claude Code session: metadata, token costs, and per-tool breakdown. Returns one row per tool used in the session with session metadata on every row.',
    'SELECT s.slug, s.project_dir, s.git_branch,
            s.started_at, s.duration,
            s.user_messages, s.assistant_messages,
            s.total_tokens, s.avg_cache_hit_rate,
            s.bash_calls, s.bash_replaceable_calls,
            tf.tool_name, tf.calls
     FROM (SELECT * FROM session_summary() WHERE session_id = $session_id) s
     LEFT JOIN (
         SELECT session_id, tool_name, sum(call_count) AS calls
         FROM tool_frequency() WHERE session_id = $session_id
         GROUP BY session_id, tool_name
     ) tf ON tf.session_id = s.session_id
     ORDER BY tf.calls DESC NULLS LAST',
    '{"session_id": {"type": "string", "description": "Session UUID to inspect"}}',
    '["session_id"]',
    'markdown'
);

;
-- Fledgling: Documentation Tools
--
-- MCP tool publications for structured markdown access.
-- Wraps macros from sql/docs.sql.
--
-- Embeds session_root at publish time (getvariable is not available
-- in MCP tool execution context). Must be loaded after sandbox.sql
-- and docs.sql, with session_root already set.
--
-- Macros without tool publications (use via query tool):
--   doc_outline

SELECT mcp_publish_tool(
    'MDSection',
    'Read a specific section from a markdown file by ID. Use the query tool with doc_outline() to discover section IDs.',
    'SELECT * FROM read_doc_section(
        _resolve($file_path),
        $section_id
    )',
    '{"file_path": {"type": "string", "description": "Path to the markdown file"}, "section_id": {"type": "string", "description": "Section ID (e.g. installation, getting-started). Use doc_outline() via query tool to discover IDs."}}',
    '["file_path", "section_id"]',
    'json'
);

;
-- Fledgling: Help Tool Publication
--
-- MCP tool publication for the skill guide.
-- Wraps the help() macro from sql/help.sql.

SELECT mcp_publish_tool(
    'Help',
    'Fledgling skill guide — tools, query-only macros, workflows, and examples. Call with no arguments for the outline. Call with a section ID for details. Use help(''macro-reference'') for the full macro catalog (available via the query tool).',
    'SELECT * FROM help(NULLIF($section, ''null''))',
    '{"section": {"type": "string", "description": "Section ID from the outline. Omit to see the table of contents."}}',
    '[]',
    'markdown'
);

;
-- Fledgling: File Access Tool Publications
--
-- MCP tool publications for file reading.
-- Wraps macros from sql/source.sql.
--
-- Uses _resolve() and _session_root() from sandbox.sql for path resolution
-- in tool templates (getvariable is not available in MCP execution context).
--
-- Git mode dispatch (commit param) is handled in tool templates because
-- git functions (git_tree, git_uri) require duck_tails, while the backing
-- macros in source.sql depend only on read_lines.
--
-- Macros without tool publications (use via query tool):
--   list_files, project_overview, read_as_table

SELECT mcp_publish_tool(
    'ReadLines',
    'Read lines from a file with optional line range, context, and match filtering. Replaces cat/head/tail.',
    'SELECT * FROM read_source(
        CASE WHEN NULLIF($commit, ''null'') IS NULL
             THEN _resolve($file_path)
             ELSE git_uri(_session_root(), $file_path, NULLIF($commit, ''null''))
        END,
        NULLIF($lines, ''null''),
        COALESCE(TRY_CAST(NULLIF($ctx, ''null'') AS INT), 0),
        NULLIF($match, ''null'')
    )',
    '{"file_path": {"type": "string", "description": "Path to the file (absolute or relative to project root)"}, "lines": {"type": "string", "description": "Line selection: single (42), range (10-20), or context (42 +/-5)"}, "ctx": {"type": "string", "description": "Context lines around selection (default 0)"}, "match": {"type": "string", "description": "Case-insensitive substring filter on line content"}, "commit": {"type": "string", "description": "Git revision (e.g. HEAD, main~2). Uses repo-relative path."}}',
    '["file_path"]',
    'json'
);

;
SET memory_limit = '4GB';
SET VARIABLE mcp_server_options = '{"built_in_tools": {"query": true, "describe": true, "list_tables": true}}';

.output
SELECT mcp_server_start(COALESCE(getvariable('transport'), 'stdio'), getvariable('mcp_server_options'));

